# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='notifications.proto',
  package='open_vario',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13notifications.proto\x12\nopen_vario\"\x13\n\x11StartNotification\"(\n\x14PressureNotification\x12\x10\n\x08pressure\x18\x01 \x01(\r\"`\n\x17TemperatureNotification\x12\x13\n\x0btemperature\x18\x01 \x01(\x11\x12\x17\n\x0fmin_temperature\x18\x02 \x01(\x11\x12\x17\n\x0fmax_temperature\x18\x03 \x01(\x11\"\xa9\x01\n\x14\x41ltitudeNotification\x12\x15\n\rmain_altitude\x18\x01 \x01(\x11\x12\x12\n\naltitude_1\x18\x02 \x01(\x11\x12\x12\n\naltitude_2\x18\x03 \x01(\x11\x12\x12\n\naltitude_3\x18\x04 \x01(\x11\x12\x12\n\naltitude_4\x18\x05 \x01(\x11\x12\x14\n\x0cmin_altitude\x18\x06 \x01(\x11\x12\x14\n\x0cmax_altitude\x18\x07 \x01(\x11\"H\n\x11VarioNotification\x12\r\n\x05vario\x18\x01 \x01(\x11\x12\x11\n\tmin_vario\x18\x02 \x01(\x11\x12\x11\n\tmax_vario\x18\x03 \x01(\x11\"\x87\x01\n\x16NavigationNotification\x12\r\n\x05speed\x18\x01 \x01(\x11\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x13\n\x0btrack_angle\x18\x04 \x01(\r\x12\x11\n\tmin_speed\x18\x05 \x01(\x11\x12\x11\n\tmax_speed\x18\x06 \x01(\x11\"\xb5\x02\n\x10SimuNotification\x12\x34\n\x08pressure\x18\x01 \x01(\x0b\x32 .open_vario.PressureNotificationH\x00\x12:\n\x0btemperature\x18\x02 \x01(\x0b\x32#.open_vario.TemperatureNotificationH\x00\x12\x34\n\x08\x61ltitude\x18\x03 \x01(\x0b\x32 .open_vario.AltitudeNotificationH\x00\x12.\n\x05vario\x18\x04 \x01(\x0b\x32\x1d.open_vario.VarioNotificationH\x00\x12\x38\n\nnavigation\x18\x05 \x01(\x0b\x32\".open_vario.NavigationNotificationH\x00\x42\x0f\n\rNotificationsb\x06proto3')
)




_STARTNOTIFICATION = _descriptor.Descriptor(
  name='StartNotification',
  full_name='open_vario.StartNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=54,
)


_PRESSURENOTIFICATION = _descriptor.Descriptor(
  name='PressureNotification',
  full_name='open_vario.PressureNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pressure', full_name='open_vario.PressureNotification.pressure', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=96,
)


_TEMPERATURENOTIFICATION = _descriptor.Descriptor(
  name='TemperatureNotification',
  full_name='open_vario.TemperatureNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='open_vario.TemperatureNotification.temperature', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_temperature', full_name='open_vario.TemperatureNotification.min_temperature', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_temperature', full_name='open_vario.TemperatureNotification.max_temperature', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=194,
)


_ALTITUDENOTIFICATION = _descriptor.Descriptor(
  name='AltitudeNotification',
  full_name='open_vario.AltitudeNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='main_altitude', full_name='open_vario.AltitudeNotification.main_altitude', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude_1', full_name='open_vario.AltitudeNotification.altitude_1', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude_2', full_name='open_vario.AltitudeNotification.altitude_2', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude_3', full_name='open_vario.AltitudeNotification.altitude_3', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude_4', full_name='open_vario.AltitudeNotification.altitude_4', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_altitude', full_name='open_vario.AltitudeNotification.min_altitude', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_altitude', full_name='open_vario.AltitudeNotification.max_altitude', index=6,
      number=7, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=366,
)


_VARIONOTIFICATION = _descriptor.Descriptor(
  name='VarioNotification',
  full_name='open_vario.VarioNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vario', full_name='open_vario.VarioNotification.vario', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_vario', full_name='open_vario.VarioNotification.min_vario', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_vario', full_name='open_vario.VarioNotification.max_vario', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=440,
)


_NAVIGATIONNOTIFICATION = _descriptor.Descriptor(
  name='NavigationNotification',
  full_name='open_vario.NavigationNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='open_vario.NavigationNotification.speed', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='open_vario.NavigationNotification.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='open_vario.NavigationNotification.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track_angle', full_name='open_vario.NavigationNotification.track_angle', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_speed', full_name='open_vario.NavigationNotification.min_speed', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_speed', full_name='open_vario.NavigationNotification.max_speed', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=578,
)


_SIMUNOTIFICATION = _descriptor.Descriptor(
  name='SimuNotification',
  full_name='open_vario.SimuNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pressure', full_name='open_vario.SimuNotification.pressure', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='open_vario.SimuNotification.temperature', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='open_vario.SimuNotification.altitude', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vario', full_name='open_vario.SimuNotification.vario', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='navigation', full_name='open_vario.SimuNotification.navigation', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Notifications', full_name='open_vario.SimuNotification.Notifications',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=581,
  serialized_end=890,
)

_SIMUNOTIFICATION.fields_by_name['pressure'].message_type = _PRESSURENOTIFICATION
_SIMUNOTIFICATION.fields_by_name['temperature'].message_type = _TEMPERATURENOTIFICATION
_SIMUNOTIFICATION.fields_by_name['altitude'].message_type = _ALTITUDENOTIFICATION
_SIMUNOTIFICATION.fields_by_name['vario'].message_type = _VARIONOTIFICATION
_SIMUNOTIFICATION.fields_by_name['navigation'].message_type = _NAVIGATIONNOTIFICATION
_SIMUNOTIFICATION.oneofs_by_name['Notifications'].fields.append(
  _SIMUNOTIFICATION.fields_by_name['pressure'])
_SIMUNOTIFICATION.fields_by_name['pressure'].containing_oneof = _SIMUNOTIFICATION.oneofs_by_name['Notifications']
_SIMUNOTIFICATION.oneofs_by_name['Notifications'].fields.append(
  _SIMUNOTIFICATION.fields_by_name['temperature'])
_SIMUNOTIFICATION.fields_by_name['temperature'].containing_oneof = _SIMUNOTIFICATION.oneofs_by_name['Notifications']
_SIMUNOTIFICATION.oneofs_by_name['Notifications'].fields.append(
  _SIMUNOTIFICATION.fields_by_name['altitude'])
_SIMUNOTIFICATION.fields_by_name['altitude'].containing_oneof = _SIMUNOTIFICATION.oneofs_by_name['Notifications']
_SIMUNOTIFICATION.oneofs_by_name['Notifications'].fields.append(
  _SIMUNOTIFICATION.fields_by_name['vario'])
_SIMUNOTIFICATION.fields_by_name['vario'].containing_oneof = _SIMUNOTIFICATION.oneofs_by_name['Notifications']
_SIMUNOTIFICATION.oneofs_by_name['Notifications'].fields.append(
  _SIMUNOTIFICATION.fields_by_name['navigation'])
_SIMUNOTIFICATION.fields_by_name['navigation'].containing_oneof = _SIMUNOTIFICATION.oneofs_by_name['Notifications']
DESCRIPTOR.message_types_by_name['StartNotification'] = _STARTNOTIFICATION
DESCRIPTOR.message_types_by_name['PressureNotification'] = _PRESSURENOTIFICATION
DESCRIPTOR.message_types_by_name['TemperatureNotification'] = _TEMPERATURENOTIFICATION
DESCRIPTOR.message_types_by_name['AltitudeNotification'] = _ALTITUDENOTIFICATION
DESCRIPTOR.message_types_by_name['VarioNotification'] = _VARIONOTIFICATION
DESCRIPTOR.message_types_by_name['NavigationNotification'] = _NAVIGATIONNOTIFICATION
DESCRIPTOR.message_types_by_name['SimuNotification'] = _SIMUNOTIFICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartNotification = _reflection.GeneratedProtocolMessageType('StartNotification', (_message.Message,), dict(
  DESCRIPTOR = _STARTNOTIFICATION,
  __module__ = 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.StartNotification)
  ))
_sym_db.RegisterMessage(StartNotification)

PressureNotification = _reflection.GeneratedProtocolMessageType('PressureNotification', (_message.Message,), dict(
  DESCRIPTOR = _PRESSURENOTIFICATION,
  __module__ = 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.PressureNotification)
  ))
_sym_db.RegisterMessage(PressureNotification)

TemperatureNotification = _reflection.GeneratedProtocolMessageType('TemperatureNotification', (_message.Message,), dict(
  DESCRIPTOR = _TEMPERATURENOTIFICATION,
  __module__ = 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.TemperatureNotification)
  ))
_sym_db.RegisterMessage(TemperatureNotification)

AltitudeNotification = _reflection.GeneratedProtocolMessageType('AltitudeNotification', (_message.Message,), dict(
  DESCRIPTOR = _ALTITUDENOTIFICATION,
  __module__ = 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.AltitudeNotification)
  ))
_sym_db.RegisterMessage(AltitudeNotification)

VarioNotification = _reflection.GeneratedProtocolMessageType('VarioNotification', (_message.Message,), dict(
  DESCRIPTOR = _VARIONOTIFICATION,
  __module__ = 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.VarioNotification)
  ))
_sym_db.RegisterMessage(VarioNotification)

NavigationNotification = _reflection.GeneratedProtocolMessageType('NavigationNotification', (_message.Message,), dict(
  DESCRIPTOR = _NAVIGATIONNOTIFICATION,
  __module__ = 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.NavigationNotification)
  ))
_sym_db.RegisterMessage(NavigationNotification)

SimuNotification = _reflection.GeneratedProtocolMessageType('SimuNotification', (_message.Message,), dict(
  DESCRIPTOR = _SIMUNOTIFICATION,
  __module__ = 'notifications_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.SimuNotification)
  ))
_sym_db.RegisterMessage(SimuNotification)


# @@protoc_insertion_point(module_scope)
