# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='requests.proto',
  package='open_vario',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0erequests.proto\x12\nopen_vario\"\x9a\x01\n\x0e\x43onnectRequest\x12N\n\x15notification_endpoint\x18\x01 \x01(\x0b\x32/.open_vario.ConnectRequest.NotificationEndpoint\x1a\x38\n\x14NotificationEndpoint\x12\x12\n\nip_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"\x13\n\x11\x44isconnectRequest\"\x14\n\x12ListSensorsRequest\"\xb3\x01\n\x13UpdateSensorRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\x14\n\nuint_value\x18\x02 \x01(\rH\x00\x12\x13\n\tint_value\x18\x03 \x01(\x11H\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x02H\x00\x12\x16\n\x0c\x64ouble_value\x18\x05 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x06 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x07 \x01(\x08H\x00\x42\x08\n\x06Values\"\x1d\n\x0bPingRequest\x12\x0e\n\x06number\x18\x01 \x01(\r\"\x98\x02\n\x0bSimuRequest\x12-\n\x07\x63onnect\x18\x01 \x01(\x0b\x32\x1a.open_vario.ConnectRequestH\x00\x12\x33\n\ndisconnect\x18\x02 \x01(\x0b\x32\x1d.open_vario.DisconnectRequestH\x00\x12\x36\n\x0clist_sensors\x18\x03 \x01(\x0b\x32\x1e.open_vario.ListSensorsRequestH\x00\x12\x38\n\rupdate_sensor\x18\x04 \x01(\x0b\x32\x1f.open_vario.UpdateSensorRequestH\x00\x12\'\n\x04ping\x18\x05 \x01(\x0b\x32\x17.open_vario.PingRequestH\x00\x42\n\n\x08Requestsb\x06proto3')
)




_CONNECTREQUEST_NOTIFICATIONENDPOINT = _descriptor.Descriptor(
  name='NotificationEndpoint',
  full_name='open_vario.ConnectRequest.NotificationEndpoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='open_vario.ConnectRequest.NotificationEndpoint.ip_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='open_vario.ConnectRequest.NotificationEndpoint.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=185,
)

_CONNECTREQUEST = _descriptor.Descriptor(
  name='ConnectRequest',
  full_name='open_vario.ConnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notification_endpoint', full_name='open_vario.ConnectRequest.notification_endpoint', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CONNECTREQUEST_NOTIFICATIONENDPOINT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=185,
)


_DISCONNECTREQUEST = _descriptor.Descriptor(
  name='DisconnectRequest',
  full_name='open_vario.DisconnectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=206,
)


_LISTSENSORSREQUEST = _descriptor.Descriptor(
  name='ListSensorsRequest',
  full_name='open_vario.ListSensorsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=228,
)


_UPDATESENSORREQUEST = _descriptor.Descriptor(
  name='UpdateSensorRequest',
  full_name='open_vario.UpdateSensorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='open_vario.UpdateSensorRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uint_value', full_name='open_vario.UpdateSensorRequest.uint_value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='open_vario.UpdateSensorRequest.int_value', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='open_vario.UpdateSensorRequest.float_value', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='open_vario.UpdateSensorRequest.double_value', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='open_vario.UpdateSensorRequest.string_value', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='open_vario.UpdateSensorRequest.bool_value', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Values', full_name='open_vario.UpdateSensorRequest.Values',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=231,
  serialized_end=410,
)


_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='open_vario.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='open_vario.PingRequest.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=441,
)


_SIMUREQUEST = _descriptor.Descriptor(
  name='SimuRequest',
  full_name='open_vario.SimuRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connect', full_name='open_vario.SimuRequest.connect', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disconnect', full_name='open_vario.SimuRequest.disconnect', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list_sensors', full_name='open_vario.SimuRequest.list_sensors', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_sensor', full_name='open_vario.SimuRequest.update_sensor', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ping', full_name='open_vario.SimuRequest.ping', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Requests', full_name='open_vario.SimuRequest.Requests',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=444,
  serialized_end=724,
)

_CONNECTREQUEST_NOTIFICATIONENDPOINT.containing_type = _CONNECTREQUEST
_CONNECTREQUEST.fields_by_name['notification_endpoint'].message_type = _CONNECTREQUEST_NOTIFICATIONENDPOINT
_UPDATESENSORREQUEST.oneofs_by_name['Values'].fields.append(
  _UPDATESENSORREQUEST.fields_by_name['uint_value'])
_UPDATESENSORREQUEST.fields_by_name['uint_value'].containing_oneof = _UPDATESENSORREQUEST.oneofs_by_name['Values']
_UPDATESENSORREQUEST.oneofs_by_name['Values'].fields.append(
  _UPDATESENSORREQUEST.fields_by_name['int_value'])
_UPDATESENSORREQUEST.fields_by_name['int_value'].containing_oneof = _UPDATESENSORREQUEST.oneofs_by_name['Values']
_UPDATESENSORREQUEST.oneofs_by_name['Values'].fields.append(
  _UPDATESENSORREQUEST.fields_by_name['float_value'])
_UPDATESENSORREQUEST.fields_by_name['float_value'].containing_oneof = _UPDATESENSORREQUEST.oneofs_by_name['Values']
_UPDATESENSORREQUEST.oneofs_by_name['Values'].fields.append(
  _UPDATESENSORREQUEST.fields_by_name['double_value'])
_UPDATESENSORREQUEST.fields_by_name['double_value'].containing_oneof = _UPDATESENSORREQUEST.oneofs_by_name['Values']
_UPDATESENSORREQUEST.oneofs_by_name['Values'].fields.append(
  _UPDATESENSORREQUEST.fields_by_name['string_value'])
_UPDATESENSORREQUEST.fields_by_name['string_value'].containing_oneof = _UPDATESENSORREQUEST.oneofs_by_name['Values']
_UPDATESENSORREQUEST.oneofs_by_name['Values'].fields.append(
  _UPDATESENSORREQUEST.fields_by_name['bool_value'])
_UPDATESENSORREQUEST.fields_by_name['bool_value'].containing_oneof = _UPDATESENSORREQUEST.oneofs_by_name['Values']
_SIMUREQUEST.fields_by_name['connect'].message_type = _CONNECTREQUEST
_SIMUREQUEST.fields_by_name['disconnect'].message_type = _DISCONNECTREQUEST
_SIMUREQUEST.fields_by_name['list_sensors'].message_type = _LISTSENSORSREQUEST
_SIMUREQUEST.fields_by_name['update_sensor'].message_type = _UPDATESENSORREQUEST
_SIMUREQUEST.fields_by_name['ping'].message_type = _PINGREQUEST
_SIMUREQUEST.oneofs_by_name['Requests'].fields.append(
  _SIMUREQUEST.fields_by_name['connect'])
_SIMUREQUEST.fields_by_name['connect'].containing_oneof = _SIMUREQUEST.oneofs_by_name['Requests']
_SIMUREQUEST.oneofs_by_name['Requests'].fields.append(
  _SIMUREQUEST.fields_by_name['disconnect'])
_SIMUREQUEST.fields_by_name['disconnect'].containing_oneof = _SIMUREQUEST.oneofs_by_name['Requests']
_SIMUREQUEST.oneofs_by_name['Requests'].fields.append(
  _SIMUREQUEST.fields_by_name['list_sensors'])
_SIMUREQUEST.fields_by_name['list_sensors'].containing_oneof = _SIMUREQUEST.oneofs_by_name['Requests']
_SIMUREQUEST.oneofs_by_name['Requests'].fields.append(
  _SIMUREQUEST.fields_by_name['update_sensor'])
_SIMUREQUEST.fields_by_name['update_sensor'].containing_oneof = _SIMUREQUEST.oneofs_by_name['Requests']
_SIMUREQUEST.oneofs_by_name['Requests'].fields.append(
  _SIMUREQUEST.fields_by_name['ping'])
_SIMUREQUEST.fields_by_name['ping'].containing_oneof = _SIMUREQUEST.oneofs_by_name['Requests']
DESCRIPTOR.message_types_by_name['ConnectRequest'] = _CONNECTREQUEST
DESCRIPTOR.message_types_by_name['DisconnectRequest'] = _DISCONNECTREQUEST
DESCRIPTOR.message_types_by_name['ListSensorsRequest'] = _LISTSENSORSREQUEST
DESCRIPTOR.message_types_by_name['UpdateSensorRequest'] = _UPDATESENSORREQUEST
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['SimuRequest'] = _SIMUREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectRequest = _reflection.GeneratedProtocolMessageType('ConnectRequest', (_message.Message,), dict(

  NotificationEndpoint = _reflection.GeneratedProtocolMessageType('NotificationEndpoint', (_message.Message,), dict(
    DESCRIPTOR = _CONNECTREQUEST_NOTIFICATIONENDPOINT,
    __module__ = 'requests_pb2'
    # @@protoc_insertion_point(class_scope:open_vario.ConnectRequest.NotificationEndpoint)
    ))
  ,
  DESCRIPTOR = _CONNECTREQUEST,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.ConnectRequest)
  ))
_sym_db.RegisterMessage(ConnectRequest)
_sym_db.RegisterMessage(ConnectRequest.NotificationEndpoint)

DisconnectRequest = _reflection.GeneratedProtocolMessageType('DisconnectRequest', (_message.Message,), dict(
  DESCRIPTOR = _DISCONNECTREQUEST,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.DisconnectRequest)
  ))
_sym_db.RegisterMessage(DisconnectRequest)

ListSensorsRequest = _reflection.GeneratedProtocolMessageType('ListSensorsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTSENSORSREQUEST,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.ListSensorsRequest)
  ))
_sym_db.RegisterMessage(ListSensorsRequest)

UpdateSensorRequest = _reflection.GeneratedProtocolMessageType('UpdateSensorRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATESENSORREQUEST,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.UpdateSensorRequest)
  ))
_sym_db.RegisterMessage(UpdateSensorRequest)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), dict(
  DESCRIPTOR = _PINGREQUEST,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.PingRequest)
  ))
_sym_db.RegisterMessage(PingRequest)

SimuRequest = _reflection.GeneratedProtocolMessageType('SimuRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIMUREQUEST,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.SimuRequest)
  ))
_sym_db.RegisterMessage(SimuRequest)


# @@protoc_insertion_point(module_scope)
