# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: responses.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='responses.proto',
  package='open_vario',
  syntax='proto3',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n\x0fresponses.proto\x12\nopen_vario\"!\n\x0f\x43onnectResponse\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x01 \x01(\x08\"\x14\n\x12\x44isconnectResponse\"\xcf\x03\n\x13ListSensorsResponse\x12\x37\n\x07sensors\x18\x01 \x03(\x0b\x32&.open_vario.ListSensorsResponse.Sensor\x1a\xa1\x01\n\x06Sensor\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x38\n\x04type\x18\x03 \x01(\x0e\x32*.open_vario.ListSensorsResponse.SensorType\x12\x43\n\nvalue_type\x18\x04 \x01(\x0e\x32/.open_vario.ListSensorsResponse.SensorValueType\"_\n\nSensorType\x12\x0e\n\nST_UNKNOWN\x10\x00\x12\x0f\n\x0bST_PRESSURE\x10\x01\x12\x12\n\x0eST_TEMPERATURE\x10\x02\x12\x0f\n\x0bST_ALTITUDE\x10\x04\x12\x0b\n\x07ST_GNSS\x10\x08\"z\n\x0fSensorValueType\x12\x0f\n\x0bSVT_UNKNOWN\x10\x00\x12\x0c\n\x08SVT_UINT\x10\x01\x12\x0b\n\x07SVT_INT\x10\x02\x12\r\n\tSVT_FLOAT\x10\x03\x12\x0e\n\nSVT_DOUBLE\x10\x04\x12\x0e\n\nSVT_STRING\x10\x05\x12\x0c\n\x08SVT_BOOL\x10\x06\"\'\n\x14UpdateSensorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0cPingResponse\x12\x0e\n\x06number\x18\x01 \x01(\r\"\x9f\x02\n\x0cSimuResponse\x12.\n\x07\x63onnect\x18\x01 \x01(\x0b\x32\x1b.open_vario.ConnectResponseH\x00\x12\x34\n\ndisconnect\x18\x02 \x01(\x0b\x32\x1e.open_vario.DisconnectResponseH\x00\x12\x37\n\x0clist_sensors\x18\x03 \x01(\x0b\x32\x1f.open_vario.ListSensorsResponseH\x00\x12\x39\n\rupdate_sensor\x18\x04 \x01(\x0b\x32 .open_vario.UpdateSensorResponseH\x00\x12(\n\x04ping\x18\x05 \x01(\x0b\x32\x18.open_vario.PingResponseH\x00\x42\x0b\n\tResponsesB\x02H\x03\x62\x06proto3')
)



_LISTSENSORSRESPONSE_SENSORTYPE = _descriptor.EnumDescriptor(
  name='SensorType',
  full_name='open_vario.ListSensorsResponse.SensorType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ST_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ST_PRESSURE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ST_TEMPERATURE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ST_ALTITUDE', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ST_GNSS', index=4, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=333,
  serialized_end=428,
)
_sym_db.RegisterEnumDescriptor(_LISTSENSORSRESPONSE_SENSORTYPE)

_LISTSENSORSRESPONSE_SENSORVALUETYPE = _descriptor.EnumDescriptor(
  name='SensorValueType',
  full_name='open_vario.ListSensorsResponse.SensorValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SVT_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVT_UINT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVT_INT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVT_FLOAT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVT_DOUBLE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVT_STRING', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SVT_BOOL', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=430,
  serialized_end=552,
)
_sym_db.RegisterEnumDescriptor(_LISTSENSORSRESPONSE_SENSORVALUETYPE)


_CONNECTRESPONSE = _descriptor.Descriptor(
  name='ConnectResponse',
  full_name='open_vario.ConnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accept', full_name='open_vario.ConnectResponse.accept', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=64,
)


_DISCONNECTRESPONSE = _descriptor.Descriptor(
  name='DisconnectResponse',
  full_name='open_vario.DisconnectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=86,
)


_LISTSENSORSRESPONSE_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='open_vario.ListSensorsResponse.Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='open_vario.ListSensorsResponse.Sensor.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='open_vario.ListSensorsResponse.Sensor.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='open_vario.ListSensorsResponse.Sensor.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_type', full_name='open_vario.ListSensorsResponse.Sensor.value_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=331,
)

_LISTSENSORSRESPONSE = _descriptor.Descriptor(
  name='ListSensorsResponse',
  full_name='open_vario.ListSensorsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensors', full_name='open_vario.ListSensorsResponse.sensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LISTSENSORSRESPONSE_SENSOR, ],
  enum_types=[
    _LISTSENSORSRESPONSE_SENSORTYPE,
    _LISTSENSORSRESPONSE_SENSORVALUETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=552,
)


_UPDATESENSORRESPONSE = _descriptor.Descriptor(
  name='UpdateSensorResponse',
  full_name='open_vario.UpdateSensorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='open_vario.UpdateSensorResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=554,
  serialized_end=593,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='open_vario.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='open_vario.PingResponse.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=595,
  serialized_end=625,
)


_SIMURESPONSE = _descriptor.Descriptor(
  name='SimuResponse',
  full_name='open_vario.SimuResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connect', full_name='open_vario.SimuResponse.connect', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disconnect', full_name='open_vario.SimuResponse.disconnect', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list_sensors', full_name='open_vario.SimuResponse.list_sensors', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_sensor', full_name='open_vario.SimuResponse.update_sensor', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ping', full_name='open_vario.SimuResponse.ping', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Responses', full_name='open_vario.SimuResponse.Responses',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=628,
  serialized_end=915,
)

_LISTSENSORSRESPONSE_SENSOR.fields_by_name['type'].enum_type = _LISTSENSORSRESPONSE_SENSORTYPE
_LISTSENSORSRESPONSE_SENSOR.fields_by_name['value_type'].enum_type = _LISTSENSORSRESPONSE_SENSORVALUETYPE
_LISTSENSORSRESPONSE_SENSOR.containing_type = _LISTSENSORSRESPONSE
_LISTSENSORSRESPONSE.fields_by_name['sensors'].message_type = _LISTSENSORSRESPONSE_SENSOR
_LISTSENSORSRESPONSE_SENSORTYPE.containing_type = _LISTSENSORSRESPONSE
_LISTSENSORSRESPONSE_SENSORVALUETYPE.containing_type = _LISTSENSORSRESPONSE
_SIMURESPONSE.fields_by_name['connect'].message_type = _CONNECTRESPONSE
_SIMURESPONSE.fields_by_name['disconnect'].message_type = _DISCONNECTRESPONSE
_SIMURESPONSE.fields_by_name['list_sensors'].message_type = _LISTSENSORSRESPONSE
_SIMURESPONSE.fields_by_name['update_sensor'].message_type = _UPDATESENSORRESPONSE
_SIMURESPONSE.fields_by_name['ping'].message_type = _PINGRESPONSE
_SIMURESPONSE.oneofs_by_name['Responses'].fields.append(
  _SIMURESPONSE.fields_by_name['connect'])
_SIMURESPONSE.fields_by_name['connect'].containing_oneof = _SIMURESPONSE.oneofs_by_name['Responses']
_SIMURESPONSE.oneofs_by_name['Responses'].fields.append(
  _SIMURESPONSE.fields_by_name['disconnect'])
_SIMURESPONSE.fields_by_name['disconnect'].containing_oneof = _SIMURESPONSE.oneofs_by_name['Responses']
_SIMURESPONSE.oneofs_by_name['Responses'].fields.append(
  _SIMURESPONSE.fields_by_name['list_sensors'])
_SIMURESPONSE.fields_by_name['list_sensors'].containing_oneof = _SIMURESPONSE.oneofs_by_name['Responses']
_SIMURESPONSE.oneofs_by_name['Responses'].fields.append(
  _SIMURESPONSE.fields_by_name['update_sensor'])
_SIMURESPONSE.fields_by_name['update_sensor'].containing_oneof = _SIMURESPONSE.oneofs_by_name['Responses']
_SIMURESPONSE.oneofs_by_name['Responses'].fields.append(
  _SIMURESPONSE.fields_by_name['ping'])
_SIMURESPONSE.fields_by_name['ping'].containing_oneof = _SIMURESPONSE.oneofs_by_name['Responses']
DESCRIPTOR.message_types_by_name['ConnectResponse'] = _CONNECTRESPONSE
DESCRIPTOR.message_types_by_name['DisconnectResponse'] = _DISCONNECTRESPONSE
DESCRIPTOR.message_types_by_name['ListSensorsResponse'] = _LISTSENSORSRESPONSE
DESCRIPTOR.message_types_by_name['UpdateSensorResponse'] = _UPDATESENSORRESPONSE
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['SimuResponse'] = _SIMURESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectResponse = _reflection.GeneratedProtocolMessageType('ConnectResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTRESPONSE,
  __module__ = 'responses_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.ConnectResponse)
  ))
_sym_db.RegisterMessage(ConnectResponse)

DisconnectResponse = _reflection.GeneratedProtocolMessageType('DisconnectResponse', (_message.Message,), dict(
  DESCRIPTOR = _DISCONNECTRESPONSE,
  __module__ = 'responses_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.DisconnectResponse)
  ))
_sym_db.RegisterMessage(DisconnectResponse)

ListSensorsResponse = _reflection.GeneratedProtocolMessageType('ListSensorsResponse', (_message.Message,), dict(

  Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), dict(
    DESCRIPTOR = _LISTSENSORSRESPONSE_SENSOR,
    __module__ = 'responses_pb2'
    # @@protoc_insertion_point(class_scope:open_vario.ListSensorsResponse.Sensor)
    ))
  ,
  DESCRIPTOR = _LISTSENSORSRESPONSE,
  __module__ = 'responses_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.ListSensorsResponse)
  ))
_sym_db.RegisterMessage(ListSensorsResponse)
_sym_db.RegisterMessage(ListSensorsResponse.Sensor)

UpdateSensorResponse = _reflection.GeneratedProtocolMessageType('UpdateSensorResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPDATESENSORRESPONSE,
  __module__ = 'responses_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.UpdateSensorResponse)
  ))
_sym_db.RegisterMessage(UpdateSensorResponse)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), dict(
  DESCRIPTOR = _PINGRESPONSE,
  __module__ = 'responses_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.PingResponse)
  ))
_sym_db.RegisterMessage(PingResponse)

SimuResponse = _reflection.GeneratedProtocolMessageType('SimuResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIMURESPONSE,
  __module__ = 'responses_pb2'
  # @@protoc_insertion_point(class_scope:open_vario.SimuResponse)
  ))
_sym_db.RegisterMessage(SimuResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
